[workspace]
members = [
    "server", "coredb", "benches"
]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false

[profile.test]
debug-assertions = true
overflow-checks = true
