[workspace]
members = [
    "server", "coredb"
]
excludes = [
    "benches", "examples/rust-apache-logs"
]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false

[profile.test]
debug-assertions = true
overflow-checks = true
