[coredb]
# Storage configuration.
storage_type = "local"              # can be "local", "aws", "gcp" or "azure"
aws_bucket_name = "dev-infino-data" # only relevant for storage type "aws"
index_dir_path = "data"

# Index configuration.
default_index_name = ".default"
segment_size_threshold_megabytes = 256
memory_budget_megabytes = 1024
retention_days = 30

[server]
port = 3000
host = "127.0.0.1"
commit_interval_in_seconds = 30
timestamp_key = "date"
labels_key = "labels"
use_rabbitmq = "no"             # specifies whether to write incoming messages to rabbitmq


# In case the server section specifies to use rabbitmq (use_rabbitmq = yes),
# configuration for rabbitmq needs to be specified. Sample configuration below.
[rabbitmq]
container_name = "infino-queue"
stream_port = 5552
listen_port = 5672
