[coredb]
# Storage configuration.
storage_type = "local"                # can be "local", "aws", "gcp" or "azure"
cloud_storage_bucket_name = "dev-infino-data"   # only relevant if storage type is "aws", "gcp", or "azure"
index_dir_path = "data"
# "cloud_storage_region" can be used to set a region for the cloud provider

# Index configuration.
default_index_name = ".default"
segment_size_threshold_megabytes = 16
memory_budget_megabytes = 1024
retention_days = 30

[server]
port = 3000
host = "0.0.0.0"
timestamp_key = "date"
labels_key = "labels"
use_rabbitmq = "no"             # specifies whether to write incoming messages to rabbitmq


# In case the server section specifies to use rabbitmq (use_rabbitmq = yes),
# configuration for rabbitmq needs to be specified. Sample configuration below.
[rabbitmq]
container_name = "infino-queue"
stream_port = 5552
listen_port = 5672
